// Code generated by mockery v2.36.0. DO NOT EDIT.

package handler

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockIWebRTCHandler is an autogenerated mock type for the IWebRTCHandler type
type MockIWebRTCHandler struct {
	mock.Mock
}

// Authorize provides a mock function with given fields: next
func (_m *MockIWebRTCHandler) Authorize(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// GetWebRTCConfig provides a mock function with given fields: w, r
func (_m *MockIWebRTCHandler) GetWebRTCConfig(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewMockIWebRTCHandler creates a new instance of MockIWebRTCHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIWebRTCHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIWebRTCHandler {
	mock := &MockIWebRTCHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
